// TIPOS
DEF VAR nome AS CHARACTER NO-UNDO. // PADRAO DE 8 POSICOES
DEF VAR nome AS CHARACTER NO-UNDO FORMAT 'x(40)'. // FORMAT PERMITE AUMENTAR A QUANTIDADE DE CARACTERES
DEF VAR nomeExtendido AS LONGCHAR NO-UNDO.

DEF VAR i32 AS INT NO-UNDO. // de -2147483648 a 2147483648
DEF VAR ig4 AS INT64 NO-UNDO. // RECOMENDADO
DEF VAR de1 AS DECIMAL NO-UNDO. // DE 40 numeros

DEF VAR data1 AS DATE NO-UNDO. //  99/99/99 format '99/99/9999'
DEF VAR data2 AS DATETIME NO-UNDO. // 99/99/99 HH:MM:SS.SSS format '99/99/9999 HH:MM:SS'
DEF VAR data3 AS DATETIME-TZ NO-UNDO. // 99/99/99 HH:MM:SS.SSS-00.00

DEF VAR logico AS LOGICAL NO-UNDO. // yes/no

DEF VAR excel AS COM-HANDLE NO-UNDO.

DEF VAR hBotao AS HANDLE NO-UNDO.
DEF VAR hFrame AS HANDLE NO-UNDO.
DEF VAR hTabela AS HANDLE NO-UNDO.

DEF VAR memoria1 AS MEMPTR NO-UNDO.

// RPW - PERMITE AGENDAR A EXECUCAO DE UM PROGRAMA
